ktor { # this block will auto-reading by ktor lib
    deployment {
        port = 8080
    }
    application {
        modules = [com.github.nepyh.ebazi.BootstrapperKt.prodModule]
    }
}
storage {
    dbUser = "admin"
    dbPassword = "password123"
}
